// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_sensitivity_cpp
LogicalVector check_sensitivity_cpp(NumericVector vals, CharacterVector ids, IntegerVector group_starts, int n_threshold, double p_rule, int nk_n, double nk_k, int n_threads);
RcppExport SEXP _rebalancedNoise_check_sensitivity_cpp(SEXP valsSEXP, SEXP idsSEXP, SEXP group_startsSEXP, SEXP n_thresholdSEXP, SEXP p_ruleSEXP, SEXP nk_nSEXP, SEXP nk_kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_starts(group_startsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threshold(n_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type p_rule(p_ruleSEXP);
    Rcpp::traits::input_parameter< int >::type nk_n(nk_nSEXP);
    Rcpp::traits::input_parameter< double >::type nk_k(nk_kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(check_sensitivity_cpp(vals, ids, group_starts, n_threshold, p_rule, nk_n, nk_k, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rebalancedNoise_check_sensitivity_cpp", (DL_FUNC) &_rebalancedNoise_check_sensitivity_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_rebalancedNoise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
