# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_sensitivity_cpp <- function(vals, ids, group_starts, n_threshold, p_rule, nk_n, nk_k, n_threads) {
    .Call(`_rebalancedNoise_check_sensitivity_cpp`, vals, ids, group_starts, n_threshold, p_rule, nk_n, nk_k, n_threads)
}

